# The URL the site will be built for
base_url = "https://nsrandom.com"

title = "Think. Learn. Write."
description = "Think. Learn. Write."

theme = "particle-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The default language; used in feeds.
default_language = "en"

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# User settings
username = "Asif Sheikh"
user_description = "Hellllllllo"
user_title = ""
email = "me@nsrandom.com"
github_username =  "nsrandom"
